export default {
  LOGIN: 'LOGIN',
  // HOME_DATA: 'HOME_DATA',
  USER_LOGOUT: 'USERLOGOUT',
  SUBMIT_TO_DO: 'TODO',
  DELETE_TO_DO: 'Delete_TODO',
  EDIT_TO_DO: 'Edit_TODO',
  EDIT_TO_DO_DATA : 'Edit_TODO_Data',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
};
